# data_ingestor.py
import csv
import os

from ml_risk_engine import cluster_village_risks


def _coerce_numeric_fields(village_record):
    numeric_fields = ["lat", "lon", "rainfall_mm", "slope_deg", "population"]
    for field in numeric_fields:
        if field in village_record and village_record[field] not in (None, ""):
            village_record[field] = float(village_record[field])
    return village_record


def process_real_gis_data(csv_file_path: str):
    """
    Reads a real CSV data spreadsheet generated by the GIS engineer
    and runs it directly through the Machine Learning system.
    """
    if not os.path.exists(csv_file_path):
        print(f"[ERROR] Could not find the file at {csv_file_path}.")
        print("Make sure Person 2 (GIS) has placed the file in this folder!")
        return None

    print(f"[INFO] Reading real spatial records from {csv_file_path}...")

    with open(csv_file_path, newline="") as csv_file:
        reader = csv.DictReader(csv_file)
        villages_list = [_coerce_numeric_fields(row) for row in reader]

    print("[ML] Computing risk clusters for real target regions...")
    ml_results = cluster_village_risks(villages_list)

    return ml_results


# --- TEST THE INGESTOR WITH A MOCK SPREADSHEET ---
if __name__ == "__main__":
    sample_data = {
        "name": ["Village_A", "Village_B", "Village_C"],
        "lat": [25.612, 25.620, 25.605],
        "lon": [85.137, 85.145, 85.120],
        "rainfall_mm": [380, 120, 290],
        "slope_deg": [52, 8, 35],
        "population": [2800, 350, 1200],
        "road_access": ["poor", "good", "moderate"]
    }

    with open("real_villages_data.csv", "w", newline="") as csv_file:
        writer = csv.DictWriter(csv_file, fieldnames=list(sample_data.keys()))
        writer.writeheader()
        for row_idx in range(len(sample_data["name"])):
            writer.writerow({key: sample_data[key][row_idx] for key in sample_data})

    results = process_real_gis_data("real_villages_data.csv")

    if results:
        print("\n--- Processed Real Records Result Sample ---")
        for v in results[:3]:
            print(f"{v['name']} -> Dynamic Cluster Tier: {v['ml_cluster_priority']}")
